"""Add relationships

Revision ID: 2c46e0ad26fc
Revises: 26346653b74f
Create Date: 2021-05-15 09:15:19.172646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c46e0ad26fc'
down_revision = '26346653b74f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_projects',
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users_projects', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'users_projects', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_projects')
    # ### end Alembic commands ###
