"""fix comments

Revision ID: 342872ae40af
Revises: 73fb3e78a2e7
Create Date: 2021-06-24 14:02:33.315475

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '342872ae40af'
down_revision = '73fb3e78a2e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('parent_id', sa.Integer(), nullable=True))
    # op.add_column('comments', sa.Column('type', postgresql.ENUM('to_the_comment', 'to_the_task', name='type'), nullable=False))
    op.create_foreign_key(None, 'comments', 'comments', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    # op.drop_column('comments', 'type')
    op.drop_column('comments', 'parent_id')
    # ### end Alembic commands ###
