"""empty message

Revision ID: 91310f08a867
Revises: 342872ae40af
Create Date: 2021-06-24 15:30:54.898627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91310f08a867'
down_revision = '342872ae40af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.add_column('comments', sa.Column('subject', sa.Text(), nullable=False))
    op.drop_constraint('comments_task_id_key', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'tasks', ['creator_id'], ['id'])
    # op.drop_column('comments', 'task_id')
    op.drop_column('comments', 'body')
    op.drop_column('comments', 'author_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('comments', sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_task_id_fkey', 'comments', 'tasks', ['task_id'], ['id'])
    op.drop_column('comments', 'subject')
    op.drop_column('comments', 'creator_id')
    # ### end Alembic commands ###
